//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Config_PLC_SIEMENS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
<<<<<<< HEAD
      /*  [global::System.Configuration.ApplicationScopedSettingAttribute()]
=======
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
>>>>>>> a0a36b5c3212f2e3f54a316800c6979999daa5ac
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HM\\MSQL;Initial Catalog=RtpConfig;Integrated Security=True")]
        public string RtpConfigConnectionString {
            get {
                return ((string)(this["RtpConfigConnectionString"]));
            }
        }*/
        
<<<<<<< HEAD
     [global::System.Configuration.ApplicationScopedSettingAttribute()]
=======
   /*   [global::System.Configuration.ApplicationScopedSettingAttribute()]
>>>>>>> a0a36b5c3212f2e3f54a316800c6979999daa5ac
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WKZP85824;Initial Catalog=RtpConfig;Integrated Security=True;Pooling=" +
            "False")]
        public string RtpConfigConnectionString {
            get {
                return ((string)(this["RtpConfigConnectionString"]));
            }
        }*/
    }
}
